# Generated by Django 5.2.7 on 2025-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granthas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
