# Generated by Django 5.1.1 on 2025-10-22 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granthas', '0002_alter_suggestion_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantha',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
