# Generated by Django 5.1.1 on 2025-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granthas', '0003_grantha_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
